Repository GDSC-SKHU/liferary-backend, pull requests merged in 2023-03, with the labels that each got.

#35 fix: redis deserializing error and add Swagger form-data function
  src/main/java/gdsc/skhu/liferary/controller/BoardPostController.java
  src/main/java/gdsc/skhu/liferary/controller/FirebaseController.java
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/controller/StudyController.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/BoardPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/CommentDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/MainPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/MemberDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/StudyDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/TokenDTO.java
  src/main/java/gdsc/skhu/liferary/domain/Member.java
  src/main/java/gdsc/skhu/liferary/domain/RedisUserDetails.java
  src/main/java/gdsc/skhu/liferary/jwt/JwtExpirationEnums.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
  src/main/java/gdsc/skhu/liferary/service/TokenUserDetailsService.java
  src/test/java/gdsc/skhu/liferary/service/BoardPostServiceTest.java
Labels: fix

#36 fix: fix UserDetails bug
  src/main/java/gdsc/skhu/liferary/domain/RedisUserDetails.java
Labels: fix

#37 chore: edit image column size
  src/main/java/gdsc/skhu/liferary/domain/MainPost.java
Labels: chore

#38 feat: change post save logic
  src/main/java/gdsc/skhu/liferary/controller/BoardPostController.java
  src/main/java/gdsc/skhu/liferary/controller/CommentController.java
  src/main/java/gdsc/skhu/liferary/controller/FirebaseController.java
  src/main/java/gdsc/skhu/liferary/controller/StudyController.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/BoardPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/CommentDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/MainPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/StudyDTO.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/CommentService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: enhancement

#39 feat: implement read member info api
  src/main/java/gdsc/skhu/liferary/controller/MemberController.java
Labels: enhancement

#40 feat: implement Google OAuth2.0 with Firebase and create post entity
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/controller/FirebaseController.java
  src/main/java/gdsc/skhu/liferary/controller/MemberController.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/MemberDTO.java
  src/main/java/gdsc/skhu/liferary/domain/Member.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
  src/main/java/gdsc/skhu/liferary/service/TokenUserDetailsService.java
  src/main/java/gdsc/skhu/liferary/token/FirebaseFilter.java
  src/test/java/gdsc/skhu/liferary/service/BoardPostServiceTest.java
Labels: enhancement

#41 chore: edit entity and DTO column
  src/main/java/gdsc/skhu/liferary/domain/DTO/MemberDTO.java
  src/main/java/gdsc/skhu/liferary/domain/Member.java
  src/test/java/gdsc/skhu/liferary/service/BoardPostServiceTest.java
Labels: chore

#42 fix: fix builder code
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
Labels: fix

#43 feat: implement global exception handler and fix CRUD
  build.gradle
  src/main/java/gdsc/skhu/liferary/controller/BoardPostController.java
  src/main/java/gdsc/skhu/liferary/controller/ExceptionController.java
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/controller/StudyController.java
  src/main/java/gdsc/skhu/liferary/domain/Category.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/BoardPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/CommentDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/MainPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/StudyDTO.java
  src/main/java/gdsc/skhu/liferary/domain/MainPost.java
  src/main/java/gdsc/skhu/liferary/domain/Member.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: enhancement

#45 fix: fix Github Actions CI/CD config file
  .github/workflows/liferary-ci-cd.yml
Labels: fix

#47 chore: edit exception code and return value of withdraw method
  src/main/java/gdsc/skhu/liferary/controller/MemberController.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
Labels: chore

#48 fix: fix post update NullPointerException
  src/main/java/gdsc/skhu/liferary/controller/ExceptionController.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: fix

#49 Feat: Modified Password function
  src/main/java/gdsc/skhu/liferary/controller/MemberController.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/MemberDTO.java
  src/main/java/gdsc/skhu/liferary/domain/Member.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
Labels: enhancement

#50 feat: add searching methods by keyword and edit api urls
  .gitignore
  build.gradle
  src/main/java/gdsc/skhu/liferary/controller/BoardPostController.java
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/controller/StudyController.java
  src/main/java/gdsc/skhu/liferary/repository/BoardPostRepository.java
  src/main/java/gdsc/skhu/liferary/repository/MainPostRepository.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/ImageService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: enhancement

#52 feat: implement searching query with Querydsl for BoardPost
  src/main/java/gdsc/skhu/liferary/domain/DTO/BoardPostDTO.java
  src/main/java/gdsc/skhu/liferary/repository/boardpost/BoardPostCustomRepository.java
  src/main/java/gdsc/skhu/liferary/repository/boardpost/BoardPostCustomRepositoryImpl.java
  src/main/java/gdsc/skhu/liferary/repository/boardpost/BoardPostRepository.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/CommentService.java
  src/test/java/gdsc/skhu/liferary/service/BoardPostServiceTest.java
Labels: enhancement

#53 fix: hotfix for search function of MainPost with category
  build.gradle
  src/main/java/gdsc/skhu/liferary/repository/mainpost/MainPostRepository.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/test/java/gdsc/skhu/liferary/service/BoardPostServiceTest.java
Labels: fix

#54 feat: implement new searching api for all types of posts
  build.gradle
  src/main/java/gdsc/skhu/liferary/controller/BoardPostController.java
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/controller/StudyController.java
  src/main/java/gdsc/skhu/liferary/repository/boardpost/BoardPostCustomRepositoryImpl.java
  src/main/java/gdsc/skhu/liferary/repository/mainpost/MainPostCustomRepositoryImpl.java
  src/main/java/gdsc/skhu/liferary/repository/mainpost/MainPostRepository.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
  src/main/java/gdsc/skhu/liferary/token/JwtFilter.java
  src/main/java/gdsc/skhu/liferary/token/TokenProvider.java
Labels: enhancement

#56 fix: fix errors in security configuration and jwt filtering logic
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/controller/ExceptionController.java
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/token/FirebaseFilter.java
  src/main/java/gdsc/skhu/liferary/token/JwtFilter.java
Labels: fix

#57 chore: edit category list
  src/main/java/gdsc/skhu/liferary/domain/Category.java
Labels: chore

#58 feat: implement study creation constraints and refactoring codes
  src/main/java/gdsc/skhu/liferary/controller/BoardPostController.java
  src/main/java/gdsc/skhu/liferary/controller/CommentController.java
  src/main/java/gdsc/skhu/liferary/controller/FirebaseController.java
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/controller/MemberController.java
  src/main/java/gdsc/skhu/liferary/controller/StudyController.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/CommentService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/MemberService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
  src/main/java/gdsc/skhu/liferary/service/TokenUserDetailsService.java
Labels: enhancement

#59 chore: edit security cors and category
  src/main/java/gdsc/skhu/liferary/configure/SecurityConfig.java
  src/main/java/gdsc/skhu/liferary/domain/Category.java
Labels: chore

#60 fix: fix paging count query error
  src/main/java/gdsc/skhu/liferary/repository/boardpost/BoardPostCustomRepositoryImpl.java
  src/main/java/gdsc/skhu/liferary/repository/mainpost/MainPostCustomRepositoryImpl.java
Labels: fix

#61 chore: edit response dto and refactoring controllers
  src/main/java/gdsc/skhu/liferary/controller/BoardPostController.java
  src/main/java/gdsc/skhu/liferary/controller/CommentController.java
  src/main/java/gdsc/skhu/liferary/controller/ExceptionController.java
  src/main/java/gdsc/skhu/liferary/controller/FirebaseController.java
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/controller/MemberController.java
  src/main/java/gdsc/skhu/liferary/controller/StudyController.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/BoardPostDTO.java
Labels: chore

#63 fix: fix getting medialink logic from Firebase Storage and token exception handling logics
  src/main/java/gdsc/skhu/liferary/service/FirebaseService.java
  src/main/java/gdsc/skhu/liferary/token/JwtFilter.java
Labels: fix

#65 fix: hotfix build error with duplicated mapping uri
  src/main/java/gdsc/skhu/liferary/controller/StudyController.java
Labels: enhancement, fix

#66 fix: hotfix for update posts with images error
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: fix

#67 fix: fix image uploading logics
  src/main/java/gdsc/skhu/liferary/domain/DTO/BoardPostDTO.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: fix

#68 fix: fix file delete logics
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/FirebaseService.java
  src/main/java/gdsc/skhu/liferary/service/ImageService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: fix

#69 fix: image uploading logics
  src/main/java/gdsc/skhu/liferary/domain/BoardPost.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/BoardPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/MainPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/StudyDTO.java
  src/main/java/gdsc/skhu/liferary/domain/MainPost.java
  src/main/java/gdsc/skhu/liferary/domain/Study.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: fix

#70 feat: implement Image API to renew image control logics
  src/main/java/gdsc/skhu/liferary/controller/BoardPostController.java
  src/main/java/gdsc/skhu/liferary/controller/CommentController.java
  src/main/java/gdsc/skhu/liferary/controller/ImageController.java
  src/main/java/gdsc/skhu/liferary/controller/MainPostController.java
  src/main/java/gdsc/skhu/liferary/controller/StudyController.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/BoardPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/ImageDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/MainPostDTO.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/StudyDTO.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/ImageService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: enhancement

#71 fix: image post update logics with images
  src/main/java/gdsc/skhu/liferary/controller/ImageController.java
  src/main/java/gdsc/skhu/liferary/domain/DTO/ImageDTO.java
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: fix

#72 fix: fix delete posts logics
  src/main/java/gdsc/skhu/liferary/service/BoardPostService.java
  src/main/java/gdsc/skhu/liferary/service/MainPostService.java
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: fix

#73 fix: fix study image control logic
  src/main/java/gdsc/skhu/liferary/service/StudyService.java
Labels: fix

#76 fix: fix text length limit
  src/main/java/gdsc/skhu/liferary/domain/BoardPost.java
  src/main/java/gdsc/skhu/liferary/domain/MainPost.java
  src/main/java/gdsc/skhu/liferary/domain/Study.java
Labels: fix

#78 fix: fix database column size limit
  src/main/java/gdsc/skhu/liferary/domain/BoardPost.java
  src/main/java/gdsc/skhu/liferary/domain/MainPost.java
  src/main/java/gdsc/skhu/liferary/domain/Study.java
Labels: fix
